# Generated by Django 2.0.3 on 2018-03-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180317_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstalledPorts',
            new_name='InstalledPort',
        ),
    ]
