# Generated by Django 2.0.3 on 2018-03-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180317_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='osstatistic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
    ]
