# Generated by Django 2.0.3 on 2018-03-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20180317_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installedport',
            old_name='port_id',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='installedport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='osstatistic',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='osstatistic',
            name='gcc_version',
        ),
    ]
