# Generated by Django 2.0.3 on 2018-03-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180317_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedport',
            name='requested',
            field=models.BooleanField(default=0),
        ),
    ]
