# Generated by Django 2.0.3 on 2018-03-17 23:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20180317_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='port',
            name='homepage',
            field=models.CharField(default='', max_length=1275),
        ),
        migrations.AddField(
            model_name='port',
            name='is_open_maintainer',
            field=models.BooleanField(default=False),
        ),
    ]
