# Generated by Django 2.0.3 on 2018-03-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20180317_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=2047, unique=True),
        ),
        migrations.AlterField(
            model_name='installedport',
            name='installed_variants',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='installedport',
            name='installed_version',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='email',
            field=models.CharField(max_length=2047, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='github_handle',
            field=models.CharField(max_length=2047, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='osstatistic',
            name='build_arch',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='osstatistic',
            name='macports_version',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='osstatistic',
            name='os_arch',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='osstatistic',
            name='os_platform',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='osstatistic',
            name='osx_version',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='osstatistic',
            name='xcode_version',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='port',
            name='homepage',
            field=models.CharField(default='', max_length=10235),
        ),
        migrations.AlterField(
            model_name='port',
            name='licenses',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=2047, unique=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='path',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='port',
            name='platforms',
            field=models.CharField(max_length=2047),
        ),
        migrations.AlterField(
            model_name='port',
            name='variants',
            field=models.CharField(default='', max_length=2047),
        ),
        migrations.AlterField(
            model_name='port',
            name='version',
            field=models.CharField(max_length=2047),
        ),
    ]
