# Generated by Django 2.0.3 on 2018-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20180317_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='homepage',
            field=models.CharField(default='', max_length=2047),
        ),
    ]
