# Generated by Django 2.0.3 on 2018-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20180323_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='epoch',
            field=models.CharField(default='0', max_length=2047),
        ),
        migrations.AlterField(
            model_name='port',
            name='revision',
            field=models.CharField(default='0', max_length=2047),
        ),
    ]
