# Generated by Django 2.0.3 on 2018-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20180323_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='platforms',
            field=models.CharField(default='', max_length=2047),
        ),
    ]
