# Generated by Django 2.0.3 on 2018-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20180323_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='revision',
            field=models.IntegerField(default=0),
        ),
    ]
